// Generated by ClangSharp
// ClangSharpPInvokeGenerator --libraryPath=openh264 --file codec/api/svc/codec_ver.h --namespace OptimeGBAServer.Media.LibOpenH264.Native --methodClassName openh264 --language c --config latest-codegen --output codec_ver.cs

namespace OptimeGBAServer.Media.LibOpenH264.Native
{
    public static partial class openh264
    {
        [NativeTypeName("const OpenH264Version")]
        public static readonly _tagVersion g_stCodecVersion = new _tagVersion
        {
            uMajor = 2,
            uMinor = 2,
            uRevision = 0,
            uReserved = 2201,
        };

        [NativeTypeName("const char *const")]
        public static string g_strCodecVer => "OpenH264 version:2.2.0.2201";
    }
}
